# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kai/Desktop/Pipeline2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kai/Desktop/Pipeline2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kai/Desktop/Pipeline2/CMakeFiles /home/kai/Desktop/Pipeline2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kai/Desktop/Pipeline2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pipeline

# Build rule for target.
Pipeline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Pipeline
.PHONY : Pipeline

# fast build rule for target.
Pipeline/fast:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/build
.PHONY : Pipeline/fast

fileprocessor/fileProcess.o: fileprocessor/fileProcess.c.o

.PHONY : fileprocessor/fileProcess.o

# target to build an object file
fileprocessor/fileProcess.c.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/fileprocessor/fileProcess.c.o
.PHONY : fileprocessor/fileProcess.c.o

fileprocessor/fileProcess.i: fileprocessor/fileProcess.c.i

.PHONY : fileprocessor/fileProcess.i

# target to preprocess a source file
fileprocessor/fileProcess.c.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/fileprocessor/fileProcess.c.i
.PHONY : fileprocessor/fileProcess.c.i

fileprocessor/fileProcess.s: fileprocessor/fileProcess.c.s

.PHONY : fileprocessor/fileProcess.s

# target to generate assembly for a file
fileprocessor/fileProcess.c.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/fileprocessor/fileProcess.c.s
.PHONY : fileprocessor/fileProcess.c.s

src/pipeLine.o: src/pipeLine.c.o

.PHONY : src/pipeLine.o

# target to build an object file
src/pipeLine.c.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/pipeLine.c.o
.PHONY : src/pipeLine.c.o

src/pipeLine.i: src/pipeLine.c.i

.PHONY : src/pipeLine.i

# target to preprocess a source file
src/pipeLine.c.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/pipeLine.c.i
.PHONY : src/pipeLine.c.i

src/pipeLine.s: src/pipeLine.c.s

.PHONY : src/pipeLine.s

# target to generate assembly for a file
src/pipeLine.c.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/pipeLine.c.s
.PHONY : src/pipeLine.c.s

src/queue.o: src/queue.c.o

.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i

.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s

.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/queue2.o: src/queue2.c.o

.PHONY : src/queue2.o

# target to build an object file
src/queue2.c.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/queue2.c.o
.PHONY : src/queue2.c.o

src/queue2.i: src/queue2.c.i

.PHONY : src/queue2.i

# target to preprocess a source file
src/queue2.c.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/queue2.c.i
.PHONY : src/queue2.c.i

src/queue2.s: src/queue2.c.s

.PHONY : src/queue2.s

# target to generate assembly for a file
src/queue2.c.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/queue2.c.s
.PHONY : src/queue2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pipeline"
	@echo "... fileprocessor/fileProcess.o"
	@echo "... fileprocessor/fileProcess.i"
	@echo "... fileprocessor/fileProcess.s"
	@echo "... src/pipeLine.o"
	@echo "... src/pipeLine.i"
	@echo "... src/pipeLine.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/queue2.o"
	@echo "... src/queue2.i"
	@echo "... src/queue2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

